<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = [
        'name', 'description', 'captain_id','num','route','period_id', 'is_lock', 
    ];

    /**
     * 追加字段
     * @var array
     */
    protected $appends = [
        'members'
    ];

    /**
     *  获取所有组员
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function members() {
        return $this->hasMany('App\User');
    }

    public function applies(){
        return $this->hasMany('App\Apply');
    }

    public static function teamCount(){
        return Group::count();
    }

    public static function successCount(){
        return Group::where('is_locked',true)->count();
    }

    /**
     * 删除队伍
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {
        $members = $this->members()->get();
        $data_enter = [
            'first' => "你的队伍已经被解散",
            'keyword1' => '队伍解散',
            'keyword2' => '解散成功',
            'keyword3' => date('Y-m-d H:i:s', time()),
            'remark'   => '还想加入队伍，请点击详情'
        ];
        $data_noenter = [
            'first' => "你申请的队伍已经被解散",
            'keyword1' => '队伍解散',
            'keyword2' => '解散成功',
            'keyword3' => date('Y-m-d H:i:s', time()),
            'remark'   => '还想加入队伍，请点击详情'
        ];
        $applies = applies();
        foreach ($applies as $apply) {
            $user = User::find($apply->apply_id);
            $user->notify($data_noenter);
            $uesr->state=1;
            $apply->delete();
            $user.save();
        }
        foreach ($members as $member) {
            $member->group_id = null;
            $member->state=1;
            $member->notify($data_enter);
            $member->save();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * 通知队长
     */
    public function notifyCaptain() {
        $data = [
            'first' => "有人申请加入你的队伍",
            'keyword1' => '队伍申请',
            'keyword2' => '正在申请',
            'keyword3' => date('Y-m-d H:i:s', time()),
            'remark'   => '点击详情，进入我的队伍查看申请信息'
        ];
        $user = User::where('id', $this->captain_id)->first();
        $user->notify($data);
    }
}
